### ISSUE TITLE
Website hangs if you long press any character

### ISSUE THREAD

**Issue by apurvns** [amsaid1989/tweet-textarea-react#3] opened 2023-01-19 09:18 UTC
Try long pressing any 1 character in textarea and website will hang .

**Comment by amsaid1989** [comment] 2023-01-20 18:35
Hi @apurvns. Thanks for reporting this issue. Will investigate it and update accordingly.

**Comment by amsaid1989** [comment] 2023-01-20 22:40
Just a quick update. I managed to reproduce this issue on my end. Currently, investigating to figure out what is causing it.

**Comment by apurvns** [comment] 2023-01-21 08:37
Thanks
Found 2 more issues 
- you can't hold backspace to delete , you have to delete one by one 
- try adding space , first time it never work. you have to press space twice and then it works normally ..

**Comment by amsaid1989** [comment] 2023-01-21 13:01
Can I ask what browser are you using and on what device? Just so I can also test with them to make sure everything is working properly when I find the source of these bugs.

**Comment by apurvns** [comment] 2023-01-21 13:02
I use Brave but I found similar issue on Chrome

**Comment by amsaid1989** [comment] 2023-01-21 13:33
I managed to reproduce the `Space` key behaviour. Hopefully, should be easy enough to fix. But I can't reproduce the `Backspace` problem at all. Tried on Chrome and Firefox. Will try on Brave when I am home.

**Comment by apurvns** [comment] 2023-01-21 14:30
I think if you solve first issue, that backspace issue might be solved as well. Because both generating similar warnings in console .. not sure just thinking . If I will also try to take a look in issue .

**Comment by amsaid1989** [comment] 2023-01-21 14:36
Not sure that solving the first issue will address the `Backspace` issue as well, because, unlike when holding a normal key, holding `Backspace` works for me as expected. However, let's see what happens when I manage to solve the first issue.
As for the `Space` issue, I think I have figured it out. Will test the solution soon, and I might even release a patch to fix it while I work on figuring out the other issues.

**Comment by amsaid1989** [comment] 2023-01-21 16:04
@apurvns Just released a patch that fixes the `Space` key issue. Still can't reproduce the `Backspace` issue, so will focus on fixing the problem were holding a key causes the website to hang and then I will try to see if there is a way for me to reproduce the `Backspace` issue.

**Comment by apurvns** [comment] 2023-01-21 16:29
That's great

**Comment by amsaid1989** [comment] 2023-01-21 18:16
@apurvns I have released another patch that should address the problem of the webpage becoming unresponsive when you press and hold a key. Can you please test it and confirm that it works for you?

**Comment by apurvns** [comment] 2023-01-21 18:33
That's great checking it now

**Comment by apurvns** [comment] 2023-01-21 18:41
checked 1.2.4 .. still same issue

**Comment by amsaid1989** [comment] 2023-01-21 18:46
Checking now on another device to see if I still see the same behaviour

**Comment by apurvns** [comment] 2023-01-21 18:50
Sorry .. I uninstalled completely and then re-installed .. its working .

**Comment by apurvns** [comment] 2023-01-21 18:51
its smooth now.. compared to previous one

**Comment by amsaid1989** [comment] 2023-01-21 19:02
That's great to hear. I have discovered another related issue. Trying to figure out what is causing it now.
Are you still experiencing the `Backspace` issue?

**Comment by apurvns** [comment] 2023-01-21 19:15
nope .. Both solved .. Great 👍

**Comment by amsaid1989** [comment] 2023-01-21 19:32
Amazing.. I will close this issue for now. The other bug I discovered is a little bit more complex, so I think it deserves a separate issue.

**Closed by amsaid1989** 2023-01-21 19:32 UTC
