### ISSUE TITLE
Shift + Enter - adds new line but resets cursor position to zero

### ISSUE THREAD

**Issue by apurvns** [amsaid1989/tweet-textarea-react#5] opened 2023-01-22 20:13 UTC

**Comment by amsaid1989** [comment] 2023-01-23 06:03
@apurvns Managed to reproduce the bug. Should be an easy one to fix. I will make `Shift+Enter` work like `Enter`. `Shift+Enter` seem to do different things in different web apps. From quick testing, it seems that Twitter just handles it the same way it handles pressing `Enter`, so I will replicate their behaviour.

**Comment by apurvns** [comment] 2023-01-24 11:39
I think you should also make twitter like content viewer. There are libraries out there which highlights mentions and tags but not having media (images,videos,links, etc) options in it and for that you have to use other library or write it yourself. Just a thought.

**Comment by amsaid1989** [comment] 2023-01-24 18:38
It definitely is a good idea in general. However, it is a bit out of scope for what I wanted from this component. It is mainly intended to be used as part of a whole to give you the ability to get the highlighting that matches exactly what you get on Twitter. I personally haven't found any libraries that does exactly that. Maybe they exist and I just couldn't find them. But the ones I managed to find never matched Twitter's behaviour exactly.
This component gives you that. You can then use it in conjunction with other components that give you the content viewing ability as well.
Maybe in the future, I will consider adding content viewing abilities. But for now, I would like to focus on a small set of features. After all, as you have noticed, the component is still not working perfectly.

**Comment by apurvns** [comment] 2023-01-26 09:05
also if you start typing and add space, it never works in first try, you have to repeatedly press space to get space working (I encountered this issue in mobile)

**Comment by amsaid1989** [comment] 2023-01-27 22:45
Mobile support isn't properly implemented yet. It is probably a good idea to add a disclaimer to the README to make this clear. I will do it tomorrow or, if you want, you can open a pull request to add it and I will merge it to the repo.

Let me know if you encounter this issue on a PC because I have never seen it happen there. Space works for me exactly as expected.

I am planning on implementing mobile support, but with limited time on my hands, I don't have an exact ETA on when I will be able to do it.

**Comment by amsaid1989** [comment] 2023-01-27 22:46
Btw, a quick update on the original issue. It is almost fixed. Most likely will release a patch tomorrow that addresses it.

**Comment by amsaid1989** [comment] 2023-01-28 17:15
This should be fixed by the latest patch. Can you please re-install the component and test it to confirm it is working for you?

**Comment by apurvns** [comment] 2023-01-29 12:11
That's great will test it soon

**Comment by amsaid1989** [comment] 2023-02-03 23:50
I am closing this for now. If you still experience this bug, let me know.

**Closed by amsaid1989** 2023-02-03 23:50 UTC
Labels: bug
